CREATE OR REPLACE FUNCTION qmeduat.IS_NUMBER( P_STR IN VARCHAR2 )
  RETURN VARCHAR2
IS
  L_STR NUMBER;
BEGIN
  L_STR := to_number( P_STR );
  RETURN 'Y';
EXCEPTION
  WHEN others THEN
    RETURN 'N';
END IS_NUMBER;
/